# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cab368bff3318669fbb2a868fad9939a509055793609346f2c8262edd1cccc0dd706dca31aa978e8b80c5eb54062ae194df9888a37549d0f0a79862cb43e9ef6

test:
  secret_key_base: bcb5e0518a85ecc0061f5eaf683f29f5e440630ef23901cd55e3a030404c3b876acac064579482d73461642dd5b294d419c25c6f9f457334581cbee50ad0236f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
